

# import pandas to let us create a path in different platforms
import pandas as pd

#import the csv path
df=pd.read_csv('c:/Users/micha/AppData/Local/Temp/Temp1_Starter_Code (2).zip/Instructions/PyBank/Resources/python-challenge.csv')

print(df)


TotalMonth = 0
total = 0
AverageChange = 0
GreatestIncreaseInProfits = 0
greatestDecreaseInProfits = 0


# I would create a few lists to store the data 
BudgetDatalist = []
BudgetChangelist = []

# Here I would open the csv file with a code that looked somehting like this
open(file) as csvfile:

# Here I would calculate the total months to store it in the list
total_months = (BudgetDataList)

# Here I would go through the list to calculate the changes between months
BudgetChange= ()

# Next I would calculate the total 
total_amount for row in BudgetDataList) 

# Next I would calculate the average change that occured using the data from the last total amount calculation and dividing it with the total months
total_change for row in BudgetDataList)
average = (TotalChange) / (TotalMonths)

#Next I would get the greatest increase and decrease using max and min
Decrease = min(BudgetDataList)
Increase = max(BudgetDataList) 

# Here is where I would print the final analysis (with the correct values)
print(TotalMonth) = 
print(total) = 
print(AverageChange) = 
print(GreatestIncreaseInProfits) = 
print(greatestDecreaseInProfits) =


# Here is where I would print the final analysis to be exported to a text file which would require a file path of some sort
